import axios from 'axios';
import { app, BrowserWindow, ipcMain, shell } from 'electron';
import { existsSync } from 'fs';
import * as dotenv from 'dotenv';
import {updateElectronApp, IUpdateDialogStrings, makeUserNotifier} from 'update-electron-app';
import { runtimeLogBroker } from './logging/LogBroker';

dotenv.config({ path: '.env.local' });
dotenv.config({ path: '.env.production' });
runtimeLogBroker.start();
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const CLERK_API_SECRET_KEY = process.env.CLERK_API_SECRET_KEY;

if (!CLERK_API_SECRET_KEY) {
  throw new Error('CLERK_API_SECRET_KEY environment variable is not set');
}

const clerkClient = axios.create({baseURL: "https://api.clerk.com/v1", headers: {Authorization: `Bearer ${CLERK_API_SECRET_KEY}`}})

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

// In development we allow multiple instances to avoid false exits while iterating.
const shouldEnforceSingleInstance = app.isPackaged || process.env.ENFORCE_SINGLE_INSTANCE === 'true';
const gotTheLock = shouldEnforceSingleInstance ? app.requestSingleInstanceLock() : true;

if (!gotTheLock) {
  console.warn('Another Stockify instance is already running; exiting this process.');
  app.quit();
} else {
  app.on('second-instance', (event, commandLine) => {
    // Someone tried to run a second instance, we should focus our window
    if (mainWindow) {
      if (mainWindow.isMinimized()) {
        mainWindow.restore();
      }
      mainWindow.focus();
    }

    // Handle the protocol URL if it exists
    const url = commandLine.find(arg => arg.startsWith('inventarum://'));
    if (url) {
      handleProtocolUrl(url);
    }
  });
}

// Function to handle protocol URL
async function handleProtocolUrl(url: string) {
  const sessionId = new URL(url).searchParams.get("sessionId");
  
  if (sessionId && mainWindow) {
    try {
      const {data: session} = await clerkClient.get(`/sessions/${sessionId}`);

      if (session) {
        console.log("Clerk session:", session);
        mainWindow.webContents.send("auth-session-received", session);
      } else {
        runtimeLogBroker.log('error', 'auth.callback_failed', 'Clerk callback returned no session', { sessionId });
        console.error("Failed to get session token:", session);
      }
    } catch (error) {
      runtimeLogBroker.log('error', 'auth.callback_failed', 'Error retrieving Clerk session from callback', { sessionId }, error);
      console.error("Error retrieving Clerk session:", error);
    }
  }
}

// Register IPC handlers
console.log('Registering IPC handlers...');
ipcMain.handle('fetch-clerk-user', async (event, user_id: string) => {
  try {
    console.log("Attempting to fetch Clerk user with ID:", user_id);
    const { data } = await clerkClient.get(`/users/${user_id}`, {
      timeout: 3000,
    });
    console.log("Successfully fetched Clerk user data");
    return data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error('Clerk API Error:', {
        status: error.response?.status,
        statusText: error.response?.statusText,
        data: error.response?.data,
        message: error.message
      });
    } else {
      console.error('Unexpected error fetching Clerk user:', error);
    }
    throw error;
  }
});

ipcMain.handle('clerk-logout', async (event, sessionId: string) => {
  try {
    console.log("Attempting to revoke Clerk session:", sessionId);
    await clerkClient.post(`/sessions/${sessionId}/revoke`);
    console.log("Successfully revoked Clerk session");
    return true;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error('Clerk Logout Error:', {
        status: error.response?.status,
        statusText: error.response?.statusText,
        data: error.response?.data,
        message: error.message
      });
    } else {
      console.error('Unexpected error during Clerk logout:', error);
    }
    throw error;
  }
});

ipcMain.handle('open-external-url', async (event, url: string) => {
  try {
    await shell.openExternal(url);
    return true;
  } catch (error) {
    console.error('Error opening external URL:', error);
    throw error;
  }
});
ipcMain.handle('get-env-variable', (event, key: string) => {
  return process.env[key] || '';
});

ipcMain.on('get-user-data-path', (event) => {
  event.returnValue = app.getPath('userData');
});

console.log('IPC handlers registered');

const dialogStrings: IUpdateDialogStrings = {
  title: 'Atualização disponível',
  detail: 'Uma nova versão do Stockify está disponível. Por favor, reinicie o aplicativo para aplicar as atualizações.',
  restartButtonText: 'Reiniciar',
  laterButtonText: 'Mais tarde',
};

const customNotifier = makeUserNotifier(dialogStrings);

updateElectronApp({
  onNotifyUser: customNotifier
})

const waitForPreloadBundle = async (): Promise<void> => {
  if (app.isPackaged) {
    return;
  }

  const preloadPath = MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY;

  if (!preloadPath || preloadPath.startsWith('http')) {
    return;
  }

  const maxAttempts = 300;
  const retryMs = 200;

  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    if (existsSync(preloadPath)) {
      return;
    }

    await new Promise((resolve) => setTimeout(resolve, retryMs));
  }

  console.warn(`Preload bundle not found after waiting: ${preloadPath}`);
};

const createWindow = async (): Promise<void> => {
  await waitForPreloadBundle();

  const useNodeInRenderer = true;

  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1400,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: !useNodeInRenderer,
      nodeIntegration: useNodeInRenderer,
    },
  }); 
  runtimeLogBroker.attachWindow(mainWindow);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Only open DevTools in development mode
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  void createWindow();
});


app.setAsDefaultProtocolClient("inventarum");

app.on('open-url', async (e, url) => {
  e.preventDefault();
  handleProtocolUrl(url);
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    void createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
